services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: drawnow-rabbit
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: drawnow
      RABBITMQ_DEFAULT_PASS: drawnow123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:7
    container_name: drawnow-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  rabbitmq_data:
  mongo_data:
